version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: opencfp-mailhog
      ports:
        - "8081:8025"

    mysql:
      image: mysql:5.7
      container_name: opencfp-mysql
      working_dir: /application
      ports:
        - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=2017_opencfp
        - MYSQL_USER=dbadmin
        - MYSQL_PASSWORD=root

    nginx:
      image: nginx:alpine
      container_name: opencfp-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
       - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: opencfp-php-fpm
      working_dir: /application
      environment:
        CFP_ENV: development
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      links:
        - mailhog
        - mysql
